[package]
name = "similars"
version = "0.2.0"
edition = "2021"
authors = ["github.com/jerryshell/similars"]

[dependencies]
clap = { version = "3.0.14", features = ["derive"] }
image = "0.24.0"

[profile.release]
lto = true
