[package]
name = "similars_cli"
version = "0.2.0"
edition = "2021"
authors = ["github.com/jerryshell"]

[dependencies]
similars_lib = { path = "../similars_lib" }
clap = { version = "3.0.14", features = ["derive"] }
