[package]
name = "similars_cli"
version = "0.2.6"
edition = "2021"
authors = ["github.com/jerryshell"]

[dependencies]
similars_lib = { path = "../similars_lib" }
clap = { version = "*", features = ["derive"] }
